/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: 475f605e1e087d91d5ecfdc54c4d6999)
interface __BaseEnv_Env {
	LEDGER: D1Database;
	GITHUB_TOKEN: string;
	OSEP_USER: string;
	OSEP_PASS: string;
	MODE: string;
	VALIDATION_ID: string;
	GITHUB_OWNER: string;
	GITHUB_REPO: string;
	GITHUB_WORKFLOW: string;
	GITHUB_REF: string;
	INTERVAL_MINUTES: string;
	SCHEDULE_START: string;
	SCHEDULE_END: string;
	OBJ_SERVICIO: string;
	OBJ_ZONA: string;
	OBJ_DEPTO: string;
	OBJ_MEDICO: string;
	OBJ_PROFESIONAL: string;
	OBJ_DOMICILIO: string;
	OBJ_HORARIO_TURNO: string;
	OBJ_DIAS_VALIDOS: string;
	OBJ_FECHA_DISP: string;
	OBJ_HORA_MIN: string;
	OBJ_HORA_MAX: string;
	OBJ_HORA_PRIORIDAD: string;
	OBJ_HORA_FLEXIBLE: string;
	OBJ_DIA_FLEXIBLE: string;
	OBJ_FECHA_FLEXIBLE: string;
	PORTAL_URL: string;
	HEADLESS: string;
	TIMEOUT_MS: string;
	STOP_AFTER_LOGIN: string;
	DRY_RUN: string;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "GITHUB_TOKEN" | "OSEP_USER" | "OSEP_PASS" | "MODE" | "VALIDATION_ID" | "GITHUB_OWNER" | "GITHUB_REPO" | "GITHUB_WORKFLOW" | "GITHUB_REF" | "INTERVAL_MINUTES" | "SCHEDULE_START" | "SCHEDULE_END" | "OBJ_SERVICIO" | "OBJ_ZONA" | "OBJ_DEPTO" | "OBJ_MEDICO" | "OBJ_PROFESIONAL" | "OBJ_DOMICILIO" | "OBJ_HORARIO_TURNO" | "OBJ_DIAS_VALIDOS" | "OBJ_FECHA_DISP" | "OBJ_HORA_MIN" | "OBJ_HORA_MAX" | "OBJ_HORA_PRIORIDAD" | "OBJ_HORA_FLEXIBLE" | "OBJ_DIA_FLEXIBLE" | "OBJ_FECHA_FLEXIBLE" | "PORTAL_URL" | "HEADLESS" | "TIMEOUT_MS" | "STOP_AFTER_LOGIN" | "DRY_RUN">> {}
}
